### ISSUE TITLE
[Feature Request] Last seen for GitHub

### ISSUE THREAD

**Issue by lonix1** [SpectricSO/stack-scripts#5]
I'm using your script for the "[last seen](https://stackapps.com/questions/9074/legacyprofiles-bringing-back-the-old-profile-stats)" feature on StackExchange, which was recently removed :rage:. It works well, and I'm really pleased I found it - thanks for making it! :grinning: 

*I was wondering whether it's possible to create such a feature for GitHub's user pages as well?*

It doesn't need to be accurate (can't be accurate unless they publish that data), but at least we can see the last date a user committed code or made a comment.

**Comment by SpectricSO** [comment]
I'm not familiar with Github's API, but this sounds like something that would

**Comment by lonix1** [comment]
I assume this isn't possible?

**Comment by SpectricSO** [comment]
This sounds like a great idea for a very helpful userscript. However, I'm not quite familiar with Github API.

For now, I'll have to close this issue as it's off topic.
