### ISSUE TITLE
SE update broke the looks of votes/answers/view (LegacyQuestions)

### ISSUE THREAD

**Issue by ghost** [SpectricSO/stack-scripts#6]
SE did an update to their website and that broke the way votes/answers/views look like (LegacyQuestions script):

![image](https://user-images.githubusercontent.com/23587065/152798783-10c69a73-6fc9-4793-bda6-5b877c1c7779.png)

**Comment by SpectricSO** [comment]
Thanks for the report!

norepro: https://stackapps.com/a/9323/76056
