### ISSUE TITLE
code-block-copier is not adapted to dark theme on SO

### ISSUE THREAD

**Issue by diogo-rossi** [SpectricSO/stack-scripts#7]
Appearance of features of [code-block-copier](https://github.com/SpectricSO/stack-scripts/tree/main/scripts/code-block-copier) is not very well adapted in the new [dark theme](https://stackoverflow.blog/2020/03/30/introducing-dark-mode-for-stack-overflow/) of Sack Overflow.

Any chances of supporting that?

## Light
![image](https://user-images.githubusercontent.com/57204023/158079800-eb1c5dbe-e6dd-495e-a426-34b4f60a3c22.png)

## Dark
![image](https://user-images.githubusercontent.com/57204023/158080071-c5be40d6-5daa-47ca-a69b-f9aae67c4261.png)

**Comment by SpectricSO** [comment]
Finally I have fixed this! Apologies for having taken nearly a year :).
[v1.1](https://github.com/SpectricSO/stack-scripts/tree/main/scripts/code-block-copier/v1.1)
