### ISSUE TITLE
Legacy Questions problem

### ISSUE THREAD

**Issue by harrym124** [SpectricSO/stack-scripts#8]
Hi,

The Legacy Questions script has served me well since February, but today has stopped working.
Apparently the CSS needs tweaking.

It would help my eyes a lot if you could update the script.

Many thanks
Harry

**Comment by SpectricSO** [comment]
It's working for me. What version of the script are you using, and on what site is it not working?

**Comment by harrym124** [comment]
Thank you for answering and for your script.
The site is superuser.com.
It seems to me that some fonts have changed, especially when writing an answer, and the user interface has suddenly become smaller.
I had to zoom-in on the browser, so I installed an extension that remembers zoom factors per-site.
I admit that I have by now grown used to the change, so it's not bothering me as much as when I started this post.

**Comment by SpectricSO** [comment]
I tried out the script on superuser and I don't see a problem. Would you mind sending a screenshot of desired/actual effect?

**Comment by harrym124** [comment]
Sorry, I don't have a screenshot of the before/desired situation, so I can't analyze what has changed.
The font changes might have only seemed like that because of the zoom problem, which I solved.
You might close this issue report.

Many thanks again for your very useful userscript, which I use daily.
